export default{
  RECEIVED_PROCESSES: 'RECEIVED_PROCESSES',
  STARED_ONE_PROCESS: 'STARED_ONE_PROCESS',
  STARED_ONE_PROCESS: 'UNSTARED_ONE_PROCESS',
  RECEIVED_SEEDS: 'RECEIVED_SEEDS',
  RECEIVED_ONE_SEED: 'RECEIVED_ONE_SEED'
}
